server:
  port: ${SERVER_PORT:8203}

spring:
  application:
    name: endpoint-security-platform

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: 计算机终端安全防护管理系统 API
    version: V1.0
